---
# Filename: create_packet_host.yml

#Purpose: Auto-generate new 'VIRL' server in Packet.net Cloud

- name: Create VIRL server
  hosts: localhost
  gather_facts: false

  tasks:

  -  packet_device:
        project_id: 02b993d3-7056-45a2-92c0-f7b08028d841
        hostnames: virl
        operating_system: custom_ipxe
        plan: baremetal_0
        facility: ewr1
        wait_timeout: 300
        user_data: |
                  #!ipxe
                  ipxe_script_url: http://packet.virl.info
                  #cloud-config
                  license_file: q2ksWwiY.virl.info.pem
                  license_pem: |
                              -----BEGIN RSA PRIVATE KEY-----
                              MIIEpAIBAAKCAQEAtI+QvWIcCrt1UwqNOWPU0uEKLlhDrOgrquRBP4CMyut9ItOA
                              3Tu3JegZIMpCZUjwLUbCWC2Kc82HI98tQ+Af3XcjeY9/HXEi/GdepFeDuceLq7r1
                              jGhTp004GWelf0/e3+PZ6eE6yXhFH7mCdtTmpHp2guybIfDlobWDI766v9VgwbAd
                              uFH0j3cP2Aa3PUJd201q+ZhHp39DXcH6kQ/iHufn83j5vwTZt7OlYWnj8SX95UOI
                              xGFwXDD5c6I/4TTplJnXGQXgV162C5YaNe6Y3cTM+hg0z+ssPVqIjB4Xe9vV7ytb
                              DtYl2FDAqxAPSlF6YOltZ5GyCy60tfF/kgZZKwIDAQABAoIBAAoM88GW9HikdqNo
                              svO+2tniLO7netzlD4kzq24debjR4uVNYJ7v9AHoKX3pxEhfBv9+MNM3tb08c4lL
                              ovlkQGHTf+YEVs8MvSXPmzUKqgptURj+Dy0BoaZuZfEEE/JCP+W2iSq7nsoYJ8Dc
                              UqbKswv0xSQEh54cCqw1rlcPBtYmsll7BV/AbY3ZBoSwH2U3h94sKLZHuz2AkTfq
                              eyskEdz8JaCnGZ/k6VpvhCweg7BiZhEH6cfHb6PRUfpW0lDK3V//YlwzQXmv/GyL
                              ehXnkDxFA0bQT8uGuOUtthMqjhB25wc0kQ0T2IG+Z/+NcMH1efo8/Bi5ciuj7dHI
                              qmtIsAECgYEAvPEaT1xXSP0yF9YEEpgvar+8sVXbiLzXw/NzoO/srq2dbW69jJ0U
                              QpAzSs0lWUUVOrYOYWNt39dSLMdrBFQtLUFEgNjZxk9hZOOXeupaaA8RB/RU4RFP
                              iGtbS+EAHunsp3ls0AuIU4qeUdhND3bN8xC+BYW00PbYdRQEPMVooYsCgYEA9KT6
                              8GkLs41RA2V5X8dlHn82at83Bmiz8Dk0TyEw4obDjvQeoolXPWAkYZ9OqRCw3wOP
                              V65W+UXs/UIN7GuLO5AxPdvZLVVcU6UxzlsutQeY2qYSlSjROXD41U8AsQ9XE6U2
                              Gp3oYIH72sGJtuLLrGLEySp00QDSN1854NaA2uECgYALx6RySjmO7WpQHiHG3wIl
                              z6p+C/JSBiQVrXoKEKtbAKwOBJeAytJWjBMGmN+5Pxthu7QN0lspV41iCVTcwjrG
                              1Yjl159MQ+q4lY/+M9pLHpVbP5qDJcclpDve8TpGsyL0Fhf4qJ9pRf008R1s12Vj
                              wCl4wqtRU/KO6h6Rg2VQnQKBgQCHEm/aPKVRRTzteyFAWH7kD6ij6QogZ76xa2QO
                              LG0pJO7kBrTDWMDqCiMMI0Dy51xARV7nMkKi7pCiY838MoR1Jm+Jj9Cgzvhi1lph
                              bMak/MTQM9EeuaKK7Gz2mN/w4l9ZYWY12+lpH1tGtISsjRuW2hF8YAyPOLzYBaOX
                              F9edAQKBgQC5mDCB+Y9pSFWmY/PUYnm2CAfNuSPfvu07tTbk8qY1ueLYtMLxThT8
                              lvHwL6IBI9uD0mEQIig/khv+78lgDFPeyTr21Jd8QbekuhcHCYshoE9gnTPwta27
                              nChfjz/y0WEZ5lsE1CIrTfkqL6rxmiJK0xW602NRPb6ALRu+dvb5Dg==
                              -----END RSA PRIVATE KEY-----
                  uwm_password: password
                  guest_password: guest
                  virl_password: VIRL

...
